// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ChartList: typeof import('./src/components/ChartList.vue')['default']
    ConfigDialog: typeof import('./src/components/ConfigDialog.vue')['default']
    DraggableResizeableItem: typeof import('./src/components/DraggableResizeableItem.vue')['default']
    File: typeof import('./src/components/File.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    PreviewItem: typeof import('./src/components/PreviewItem.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    ToolBarSwitcher: typeof import('./src/components/ToolBarSwitcher.vue')['default']
  }
}

export { }
